# Generated by Django 2.1.4 on 2019-05-06 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20190506_0951'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studen',
            new_name='Student',
        ),
    ]
